### ISSUE TITLE
Support for complex Choices rules

### ISSUE THREAD

**Issue by sumlbel** [oshikiri/fake-step-functions#18]
This is a great lib.
It would be great to add complex Choices rules support (And/Or/Not/...Path ones) though.
I can assist with that.

**Comment by oshikiri** [comment]
Hi @sumlbel, thank you for your interest.

I saw your mail. Could you please try to send a pull request from your forked repository?

cf. https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by sumlbel** [comment]
Hi Takamasa, thank you for your reply.

Here is the pull request:
https://github.com/oshikiri/fake-step-functions/pull/19

Best regards,
Stepan.

**Comment by oshikiri** [comment]
Thank you for your pull request. I will check it

**Comment by sumlbel** [comment]
Added with 0.4.0

**Comment by oshikiri** [comment]
Thank you for your contribution!
