### ISSUE TITLE
Add executed states to field for validating execution path in tests.

### ISSUE THREAD

**Issue by LiamRiddell** [oshikiri/fake-step-functions#28]
## User Story
We have quite complicated StepFunctions which have many branching choices. A nice feature that I saw with one of the other libraries was an execution path of the states. This allows us to test for the execution path and not just the end state.

## Crude Implementation
Reading the code, I think that this could be crudely implemented into the `runState` function where by before the `Switch` statement we have an array property which we push the state name into each time the function is called.

![image](https://user-images.githubusercontent.com/3812154/207597427-c1541208-f928-4689-82b7-47e1070fdd21.png)

## Use Case

```ts
    test('should not throw an Error', async () => {
      const definition = require('./fixtures/definitions/pass-state-undefined-resultpath.json');
      const fakeStateMachine = new FakeStateMachine(definition, {});

      await fakeStateMachine.run({
        changed: 'TBD',
        unchanged: 'unchanged',
      });

      expect(fakeStateMachine.executionPath).toEqual([
        "Pass0",
        "Choice1",
        "Branch2",
        "Done"
      ]);
    });
```

**Comment by oshikiri** [comment]
It looks good to me :+1:
